// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// double_bootstrap_bias_cpp
List double_bootstrap_bias_cpp(NumericVector y0_s1, NumericVector y1_s1, NumericVector y2_s1, int d, int n1, int B1, int B2, Function dose_select, std::string alternative, double alpha, std::string htest_method);
RcppExport SEXP _BootSeam_double_bootstrap_bias_cpp(SEXP y0_s1SEXP, SEXP y1_s1SEXP, SEXP y2_s1SEXP, SEXP dSEXP, SEXP n1SEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP dose_selectSEXP, SEXP alternativeSEXP, SEXP alphaSEXP, SEXP htest_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y0_s1(y0_s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_s1(y1_s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_s1(y2_s1SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< int >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< Function >::type dose_select(dose_selectSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::string >::type htest_method(htest_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(double_bootstrap_bias_cpp(y0_s1, y1_s1, y2_s1, d, n1, B1, B2, dose_select, alternative, alpha, htest_method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BootSeam_double_bootstrap_bias_cpp", (DL_FUNC) &_BootSeam_double_bootstrap_bias_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_BootSeam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
