# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

double_bootstrap_bias_cpp <- function(y0_s1, y1_s1, y2_s1, d, n1, B1, B2, dose_select, alternative, alpha, htest_method) {
    .Call(`_BootSeam_double_bootstrap_bias_cpp`, y0_s1, y1_s1, y2_s1, d, n1, B1, B2, dose_select, alternative, alpha, htest_method)
}

